### ISSUE TITLE
creating user profiles partition during QWT install fails

### ISSUE THREAD

**Issue by 100111001** [elliotkillick/qvm-create-windows-qube#34] opened 2021-09-11 18:20 UTC
Thank you very much for this project. I tried it with the current win10x64 and I'm currently stuck several times at the same step:
[i] Preparing Windows media for automatic installation...
[i] Starting creation of win10-orig_01
[i] Commencing first part of Windows installation process...
[i] Commencing second part of Windows installation process...
[i] Preparing Qubes Windows Tools for automatic installation...
[i] Installing Qubes Windows Tools...

During the windows tools installation the volume d: fails during formating with ntfs. By trying to format it manually (format d: /fs:ntfs /Q) the following message is displayed:
"QuickFormatting 2.0 GB
Starting offset of the thinly provisioned or DAX partition is not aligned to a cluster boundary. Partition is 512 bytes aligned. To format with specified cluster size, align the partition to 4 KB.
Format failed."

The installation of Windows Tools cannot be continued.

Seems to be related to this issue: https://github.com/QubesOS/qubes-issues/issues/5768

Any ideas how to resolve this?

**Comment by elliotkillick** [comment] 2021-10-14 01:48
This is a duplicate of #25. Note that it's not a blocking issue, installation will continue as normal upon exiting out of the error window (or `prepare-volume.exe`).  Please see [here](https://github.com/elliotkillick/qvm-create-windows-qube#windows-10-and-windows-server-2019).

Additionally, see the video in the README if you want a visual demonstration of the fix being done.

**Closed by elliotkillick** 2021-10-14 01:48 UTC
