### ISSUE TITLE
Windows 7 : Drivers are not properly installed, usb not working

### ISSUE THREAD

**Issue by 54646546** [elliotkillick/qvm-create-windows-qube#57] opened 2022-08-11 12:40 UTC
Installation worked properly however usb is not working in the vm and following driver seems to have problems in the windows device manager : 

- Universal Serial Bus (USB) Controller
- XP9001 XENBUS VBD
- XP0001 XENBUS VIF

**Comment by im7mortal** [comment] 2023-03-07 01:31
I can confirm it. 

### Usb
![USB](https://user-images.githubusercontent.com/5336231/223295267-baddf6d6-7d8e-4487-904c-67e33e586bf5.png)

### Drivers 
![DRIVERS](https://user-images.githubusercontent.com/5336231/223295344-b3a8f13b-69e7-4572-8577-e6f10ec3b5d2.png)

### Videocard
![VIDEO_MEMORY](https://user-images.githubusercontent.com/5336231/223295368-97979bf3-084f-468a-9a60-cb3c08f21921.png)

I don't need usb but I really wanted to run GTA Vice City. And I am facing this error. So far I didn't figure out how to resolve it. Before I tried to run it on debian with `wine` and I afterm many pains I could run it but it wasn't playable. It always stack in menu.
I am not sure how to fix it yet. I have separate `steam` cube and I run heavier games there.  


***Any help with 'Qubes Video Driver' is appreciated. Thank you!***

**Comment by elliotkillick** [comment] 2023-06-10 07:11
USB passthrough support is a new feature that I was added using QEMU not too long ago (but after Windows 7 EOL): https://github.com/QubesOS/qubes-issues/issues/5802

I haven't installed a Windows 7 VM not long since EOL, but I've never seen those kind of warnings in Device Manager (except one).

GPU passthrough is definitely working on Windows 10. I've already done it with a GTX 1050 Ti and it works great. Windows 7 (especially with the GuiVM driver) is a different story though because it's EOL now. Your graphics card drivers may have very well dropped support for Windows 7 by now. Use Windows 10 LTSC if you want a more slimmed down system.

Overall, this seems like an upstream issue and for that reason I'm closing it (feel free to raise this on the Qubes OS GitHub Issues though).

**Closed by elliotkillick** 2023-06-10 07:11 UTC
