### ISSUE TITLE
Windows Server 2016 needs Dot Net from Server Manager / Features for QWT

### ISSUE THREAD

**Issue by bowtiediguana** [elliotkillick/qvm-create-windows-qube#38] opened 2021-09-24 22:02 UTC
QWT install does not complete as .NET 3.5 needed to be installed from Sever Manager.
Windows Server 2016 throws a source error (0x800f081f) when attempting to do so. (likely because the airgap hasn't been removed yet)

Expected behavior: QWT and dependencies install successfully.

Commenting lines 302-304 (qvm-firewall rules to maintain airgap) to fix the issue, understanding that the VM may try phoning home to MSFT if this is done.

May wish to investigate building the CAB into the ISO and running the DSIM e.g. https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/deploy-net-framework-35-by-using-deployment-image-servicing-and-management--dism

**Comment by elliotkillick** [comment] 2021-10-14 02:41
This is a duplicate of #13. QWT installs and works correctly anyway, you can simply ignore that window. See [here](https://github.com/elliotkillick/qvm-create-windows-qube#all-oss-except-windows-7-and-windows-server-2008-r2). See the issue as well for what here is specific to Windows Server 2016.

**Closed by elliotkillick** 2021-10-14 02:41 UTC
