### ISSUE TITLE
An unexpected error has occured! Exiting...

### ISSUE THREAD

**Issue by fk3ma** [elliotkillick/qvm-create-windows-qube#35] opened 2021-09-17 03:53 UTC
_I don't know how to copy and paste out of dom0 so I will just retype this manually_

$ qvm-create-windows-qube -n sys-whonix -oyw -i win10x64-enterprise-eval.iso -a win10x64-enterprise-eval.xml win10-work
Preparing Windows media for automatic installation ... 
Starting creation of win10-work ...
Commencing first part of Windows installation process ... 
Commencing second part of Windows installation process ... 
Preparing Qubes Windows Tools for automatic installation ... 
[!] An unexpected error as occured! Exiting ...

**Comment by cm157** [comment] 2021-09-19 20:50
I know exactly what the issue is. You created the windosx-mgmt template on fedora 32 and then you switched all your template bases to fedora 33. Revert that template back to fedora 32.

**Comment by elliotkillick** [comment] 2021-10-14 02:10
The most likely issue is that your `windows-mgmt` ran out of disk space causing the creation of the QWT automatic installation ISO to fail. Try making sure your VM has ample space in the private volume and report back if increasing it doesn't fix the problem.

@cm157 No, `fedora-33` definitely works. It's the same template my `windows-mgmt` is using.

**Comment by anon8675309** [comment] 2021-11-05 16:10
I'm getting this same "An unexpected error has occurred! Exiting..." message when I run install.sh

In my case, the error appears to be related to PGP signatures that are checked immediately after cloning the `qvm-create-windows-qube` repository.  After printing `Please check for a "Good signature" from GPG (Verify it out-of-band if necessary)...`, there's gpg output that includes the following:

> gpg: key F83DD5F2: no valid user IDs
> gpg: this may be caused by a missing self-signature
> gpg: Total number processed: 1
> gpg:           w/o user IDs: 1
> [!] An unexpected error has occurred! Exiting...

I can open a new ticket if this is a different error from what was originally posted in this issue.  I'm using a fully patched Qubes 4.0 installation and fedora-29.  I have about 300GB of disk space available.

**Comment by elliotkillick** [comment] 2021-11-06 00:01
@anon8675309 Thanks for providing ample information so I can accurately diagnose your problem. The issue arises due to the very out-of-date version of Fedora you're using (29). You shouldn't be using that version because it's no longer getting updates as of November 26th, 2019 (this includes security updates). Please upgrade to Fedora 30 or higher to fix it.

**Comment by elliotkillick** [comment] 2023-06-10 06:36
Closing as Brendan is probably correct here.

**Closed by elliotkillick** 2023-06-10 06:36 UTC
Labels: question
