### ISSUE TITLE
Depend on tabit-pro qubes-windows-tools instead of ITL's

### ISSUE THREAD

**Issue by tlaurion** [elliotkillick/qvm-create-windows-qube#24] opened 2020-12-28 05:25 UTC
https://github.com/tabit-pro/Qway-qubes-repo/tree/master/qubes-windows-tools
https://groups.google.com/g/qubes-devel/c/lreMRsAPjnI

**Comment by elliotkillick** [comment] 2021-04-01 04:54
This looks to be a duplicate of https://github.com/elliotkillick/qvm-create-windows-qube/issues/15.

Please feel free to work on this integration in your own local repo.

**Closed by elliotkillick** 2021-04-01 04:54 UTC
